### ISSUE TITLE
Is there a way I can add p-value in the Adjusted Survival Curves for Cox Proportional Hazards Model?

### ISSUE THREAD

**Issue by ningyile** [RobinDenz1/adjustedCurves#11]
Thank you for creating a great package!

I wanted to ask if it is possible to add p-value in the plot?

I noticed that neither `ggadjustedcurves` of [survminer](http://rpkgs.datanovia.com/survminer/index.html) nor `adjustedsurv` function has a parameter for adding p-value. 

Is it feasible to extract the p-value of the Cox model and add it to the plot object and then render it? 

Thank you for your help!

**Comment by RobinDenz1** [comment]
Thank you.

As you probably know, a p-value is the probability to observe a test statistic that is at least as big or more extreme than the actually observed test statistic, given that the null hypothesis is true. To calculate a p-value, it is therefore necessary to define the null and alternative hypothesis as well as the test statistic.

So my question would be, what exactly do you want to test? What should the p-value be about? This is not a trivial question. The `adjustedCurves` package offers a few ways to test the difference between two confounder-adjusted survival curves. First, you could use the `adjusted_curve_diff` function to test if the survival probabilities at some specific point in time are equal. Secondly, you could use the `adjusted_rmst` function to test if the areas under the survival curves up to a specific point in time are equal (there is no p-value for this, but confidence intervals). Third, you could use the `adjusted_curve_test` function, which tests if the area *between* two survival curves is equal. That function is, however, based on bootstrapping and is more or less experimental.

The only other hypothesis test to compare adjusted survival curves that I know of is the log-rank test based using IPTW implemented in the `RISCA` package (function `ipw.log.rank`). This only works if you are using the IPTW method with two possible treatments.

Since it is unclear what kind of p-value would be generally of interest, there is no direct option to add it to the plot produced by `plot.adjustedsurv`. However, the `plot_curve_diff` function of my package directly allows you to add the `adjusted_curve_test` based p-value. If you want to add some p-value to the `plot.adjustedsurv` output, you could use the `geom_text_npc` function from the `ggpp` package. This works because the output is a standard `ggplot` object and is in fact what I used in the `plot_curve_diff` function to add p-values.

Hope this helps.

**Comment by ningyile** [comment]
> Thank you.
> 
> As you probably know, a p-value is the probability to observe a test statistic that is at least as big or more extreme than the actually observed test statistic, given that the null hypothesis is true. To calculate a p-value, it is therefore necessary to define the null and alternative hypothesis as well as the test statistic.
> 
> So my question would be, what exactly do you want to test? What should the p-value be about? This is not a trivial question. The `adjustedCurves` package offers a few ways to test the difference between two confounder-adjusted survival curves. First, you could use the `adjusted_curve_diff` function to test if the survival probabilities at some specific point in time are equal. Secondly, you could use the `adjusted_rmst` function to test if the areas under the survival curves up to a specific point in time are equal (there is no p-value for this, but confidence intervals). Third, you could use the `adjusted_curve_test` function, which tests if the area _between_ two survival curves is equal. That function is, however, based on bootstrapping and is more or less experimental.
> 
> The only other hypothesis test to compare adjusted survival curves that I know of is the log-rank test based using IPTW implemented in the `RISCA` package (function `ipw.log.rank`). This only works if you are using the IPTW method with two possible treatments.
> 
> Since it is unclear what kind of p-value would be generally of interest, there is no direct option to add it to the plot produced by `plot.adjustedsurv`. However, the `plot_curve_diff` function of my package directly allows you to add the `adjusted_curve_test` based p-value. If you want to add some p-value to the `plot.adjustedsurv` output, you could use the `geom_text_npc` function from the `ggpp` package. This works because the output is a standard `ggplot` object and is in fact what I used in the `plot_curve_diff` function to add p-values.
> 
> Hope this helps.

Thank you for your detailed and prompt reply! It seemed that I have another problem. I find the output of adjusted survival curve using the `adjustedsurv` function seems a little bit slower than the `ggadjustedcurves` function. It took about 35-40 minutes to compute in my case with the `adjustedsurv` function. I noticed that this package seems to rely on the `doParallel` package, and I was wondering if I could use multithreading to speed up the output of adjusted survival curve.

**Comment by ningyile** [comment]
> Thank you.
> 
> As you probably know, a p-value is the probability to observe a test statistic that is at least as big or more extreme than the actually observed test statistic, given that the null hypothesis is true. To calculate a p-value, it is therefore necessary to define the null and alternative hypothesis as well as the test statistic.
> 
> So my question would be, what exactly do you want to test? What should the p-value be about? This is not a trivial question. The `adjustedCurves` package offers a few ways to test the difference between two confounder-adjusted survival curves. First, you could use the `adjusted_curve_diff` function to test if the survival probabilities at some specific point in time are equal. Secondly, you could use the `adjusted_rmst` function to test if the areas under the survival curves up to a specific point in time are equal (there is no p-value for this, but confidence intervals). Third, you could use the `adjusted_curve_test` function, which tests if the area _between_ two survival curves is equal. That function is, however, based on bootstrapping and is more or less experimental.
> 
> The only other hypothesis test to compare adjusted survival curves that I know of is the log-rank test based using IPTW implemented in the `RISCA` package (function `ipw.log.rank`). This only works if you are using the IPTW method with two possible treatments.
> 
> Since it is unclear what kind of p-value would be generally of interest, there is no direct option to add it to the plot produced by `plot.adjustedsurv`. However, the `plot_curve_diff` function of my package directly allows you to add the `adjusted_curve_test` based p-value. If you want to add some p-value to the `plot.adjustedsurv` output, you could use the `geom_text_npc` function from the `ggpp` package. This works because the output is a standard `ggplot` object and is in fact what I used in the `plot_curve_diff` function to add p-values.
> 
> Hope this helps.

Thank you for your detailed and prompt reply! It seemed that I have another problem. I find the output of adjusted survival curve using the `adjustedsurv` function seems a little bit slower than the `ggadjustedcurves` function. It took about 35-40 minutes to compute in my case with the `adjustedsurv` function. I noticed that this package seems to rely on the `doParallel` package, and I was wondering if I could use multithreading to speed up the output of adjusted survival curve.

**Comment by RobinDenz1** [comment]
No problem.

Could you provide the code that you used? Otherwise I have no way of knowing what the problem could be. Usually the `adjustedsurv` function should be faster than `ggadjustedcurves`, but it depends on what `method` you are using and what kind of arguments you used.

If you use `conf_int=TRUE` with `method="direct"` and have a very big dataset with many points in time at which an event occurs it may take a long time. You can make it faster by using `conf_int=FALSE` or by specifying the `times` argument. The multithreading implemented in the `adjustedsurv` function only helps if you are using `bootstrap=TRUE`.

**Comment by ningyile** [comment]
As I wrapped the codes with a customised function, and many many lines that don't apply to the issue. I select the key codes in my R script were displayed as follows (if you think these codes can not reproduce the issue, I will provide the data and streamline some of the non-essential code to investigate in further):
```R
## Survey-weighted Cox model
cox_res = svycoxph(fml, design = ipw_svydesign, data = df, x = T) 

### Adjusted survival curves of survey-weighted Cox model
adjsurv = adjustedsurv(data = df,
                                        variable = "Group",
                                        ev_time = los,
                                        event = outcome,
                                        method = "direct",
                                        outcome_model = cox_res,
                                        conf_int = F,
                                        bootstrap = T,
                                        n_boot = 100)

adjtest = adjusted_curve_test(adjsurv, from=0, to=1)

p1 = plot(adjsurv, conf_int = F)

p2 = ggadjustedcurves(cox_res, data = df, method = "conditional", variable = "Group")
```

**Comment by RobinDenz1** [comment]
That is more than enough information for me, thank you. The `adjustedsurv` function takes longer than the `ggadjustedcurves` function here because you are using bootstrapping, which essentially means that it has to do the calculations `n_boot=100` times as opposed to one time. You can use the `n_cores` argument to let it run on multiple processor cores at once which should give you a considerable speed-up.

In general however, I would recommend a different way of doing this. Currently you are fitting a weighted cox model and use this model to perform g-computation (`method="direct"`). In simulation studies I conducted, this always produced biased results. I would recommend using the ipw weights directly with `method="iptw_km"`. You could do something like this:

```r
weights <- # your code to obtain those here

adjsurv = adjustedsurv(data = df,
                       variable = "Group",
                       ev_time = los,
                       event = outcome,
                       method = "direct",
                       treatment_model = weights,
                       conf_int = F,
                       bootstrap = T,
                       n_boot = 100,
                       n_cores = parallel::detectCores()-1 #use all but one processor core
)

adjtest = adjusted_curve_test(adjsurv, from=0, to=1)

p1 = plot(adjsurv, conf_int = F)
```
You should also check if 100 bootstrap samples is actually enough using the `plot` method of the `adjusted_curve_test` function.

**Comment by ningyile** [comment]
You are so kind! Respect from China! You help me a lot! Thank you so much, buddy! I pass the `PSM model` to the `treatment_model`, and a new error came up: "Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE". Have you ever encountered related things before?  I run these codes on Rstudio server, Ubuntu 22.04.

**Comment by RobinDenz1** [comment]
I am happy to help if I can! Unfortunately I have never seen that error message. It is kind of suprising to me because the package is tested on Ubuntu as well. ´Could you provide a reproducible example of the error? Otherwise I am unable to debug it. Does your code run if you don't use the `n_cores` argument?

The `n_boot` parameter specifies how many bootstrap replications to perform. As such, it can be any positive integer > 1, although it only makes sense with reasonably high values. The documentation uses a low number to keep the code fast, which is a requirement made by CRAN.

**Comment by ningyile** [comment]
I uploaded the code and data in [test.zip](https://github.com/RobinDenz1/adjustedCurves/files/11285453/test.zip). You can test it on your ubuntu. PSM was estimated using logistic regression, and `psm_model` and `ps_fml` were the model and formula of PSM respectively, which were stored as object in Rdata. 

PS: I know it takes a lot of time and effort to develop R packages to answer users' questions. Do you have PayPal id or sponsored links or QR codes(Wechat or Alipay were popular in China) like those of other open-source authors (I searched your name on Facebook and Twitter, but couldn't find such sponsored links)? Can I buy you a cup of coffee for my support? Thank you very much. I have been troubled by this problem all day. Thank you for your help.

**Comment by ningyile** [comment]
Dude, you're so nice. I will undoubtedly cite your paper in my research. With great respect again, thank you very much!
