### ISSUE TITLE
At risk / events table on adjustedCurves plot

### ISSUE THREAD

**Issue by drs81** [RobinDenz1/adjustedCurves#16]
Hi,
Would it be possible to output a table of at risk / events below the adjusted cumulative incidence / survival plot. Similar to those that can be produced in tidycmprsk:
https://mskcc-epi-bio.github.io/tidycmprsk/
I guess these at risk / events numbers will be predicted values as opposed to the raw data if they were to "align" with the adjusted curve. 
Thanks.

**Comment by RobinDenz1** [comment]
I have answered this question in #14, there isn't really much of a point to do this because the "adjusted number at risk" only exists when using `method="iptw_km"` (and maybe `method="iptw"` in `adjustedcif`). However, if you have an idea how to estimate sensible values for these parameters when using different methods I would be happy to see what I can do.
