### ISSUE TITLE
adjustedcif plot customization

### ISSUE THREAD

**Issue by devanto86** [RobinDenz1/adjustedCurves#23]
Hi,
many thanks for this package and for your work!

I'm using adjustedcif for plotting curves for a competing risk outcome with "iptw_pseudo" and providing custom weights as explained in cif_iptw_pseudo examples.

I have few (probably silly) questions for result visualization:
- could it be possibile to plot not the cif curve but 1-cif (kind of survival probability)? I do not see any fun argument in plot.adjustedcif that could do that
- i'd like to add risk table below the plot, but i do not think the function can address this issue. Could it be possibile to extract the code under plot.adjustedcif so that i can customize it accordingly (e.g. plotting curves with ggsurvfit package, that would easily allow to add risk tables, etc etc).
Thanks for your support.

**Comment by RobinDenz1** [comment]
Glad you like it!

To answer your questions:
1.) This is sadly impossible. Even in the unadjusted case this cannot be done using current methods.
2.) When using `method="iptw_pseudo"`, there is no such thing as a risk table. The method is based on calculating pseudo-values for each person and then taking a weighted mean of these values. Numbers at risk are not used at any point in the calculation of the output. In fact, none of the implemented methods in `adjustedcif` use risk tables under the hood, so there is nothing to show here. For competing risks data, that is pretty normal though, even in the unadjusted case.

Hope this helps! If you have further questions please don't hesitate to ask. I would also highly appreciate if you cited the associated article if you end up using the package. Thanks!

**Comment by devanto86** [comment]
Thanks for your quick reply.
Given the above-mentioned task (i.e. adjustedcif for plotting curves for a competing risk outcome with "iptw_pseudo" and providing custom weights), how can i calculate a p-value for the difference of cif curves between a dichotomous variable (e.g. male vs female)? I tried with adjusted_curve_test, but this requires adjustedcif to be called with bootstrap, but adjustedcif with iptw_pseudo and custom weights cannot be called with bootstrap=TRUE.
Can you suggest any effective way?
Thanks

**Comment by RobinDenz1** [comment]
There are a few possibilities you could pursue. First of all, how are the weights calculated? If you are using a logistic regression model or if the weights could be calculated using `weightit()`, you could change the `treatment_model` argument accordingly, which will then allow bootstrapping. (Note that bootstrapping is not allowed for directly passed weight vectors because the weights need to be estimated for each bootstrap sample separately). Once you have bootstrap samples you could use different methods to compare the curves. You could compare differences in restricted mean time lost (`adjusted_rmtl()` with difference=TRUE), test if the area between the curves is zero in some interval (`adjusted_curve_test()`) or check if the difference is statistically difference from zero at certain points in time (`adjusted_curved_diff()`).

If you cannot use bootstrapping at all, the only method that still works would be the option i mentioned last, comparing the curves at specific points in time. This works even without bootstrapping when `conf_int=TRUE` was used successfully in the original `adjustedcif()` call.
