### ISSUE TITLE
NA value when using strata on coxph call

### ISSUE THREAD

**Issue by Olimpieri** [RobinDenz1/adjustedCurves#4]
Hi, 
when using method = direct with a cox model obtained using cozph and strata() on a variable with non-proportional hazard, I obtain an outcome with NA value in the adjusted survival. Of interest, these NA values are reported at the end of the curves for each group (3 NA values, one for each group, last value of the curve).
Thanks,
Pier Paolo

**Comment by RobinDenz1** [comment]
Thank you for bringing this to my attention. Could you perhaps provide a reproducible example? Without that it is sadly impossible for me to figure out what is happening.

**Comment by RobinDenz1** [comment]
Thanks for the reproducible example. When using `method="direct"` with a `coxph()` model, the `ate()` function of the `riskRegression` package is used internally to estimate the survival probabilities. It is therefore an "issue" in that function, not in the `adjustedsurv()` function.

Since I did not develop the `riskRegression` package I can't say for sure, but I suspect that the reason is as follows: when you specify `strata(country)` you are essentially specifying that the baseline hazard should be stratified by `country`. Internally, the `ate()` function does exactly as you requested. The issue is now, though, that for some countries the last observation time is smaller than the maximal observation time. For example, the largest `age_at_onset` for `country="Australia"` is 69. That means the baseline hazard can only be estimated up to that point for people with that level.

When making predictions for individuals with `country="Australia"` for points in time after 69, the `riskRegression` package simply returns `NA`, because there is no baseline hazard estimate that could be used here without doing some ad-hoc extrapolation that might lead to bias. Thus, `NA` is returned as an estimate for the whole adjusted survival curve.

In my eyes this is the correct procedure. If you want the baseline hazard to vary by `country`, this is something you just have to deal with. I suspect that the `survminer` package either ignores the `strata()` terms or that it performs some unjustified extrapolation of the baseline hazard, although I am just guessing here. Either way, I would not trust the `survminer` estimates.

**Comment by Neurarian** [comment]
Thank you for your detailed answer. This definitely clarified the issue. The survminer package does not seem to drop the `strata()` terms, as the output does look different with and without. So I do wonder what it is doing internally. Thank you for your recommendation.
