### ISSUE TITLE
Could this package achieve covariate adjusted KM survival curves for competing risk events analysis?

### ISSUE THREAD

**Issue by jiangaimin1995** [RobinDenz1/adjustedCurves#6]
This is a very exellent package. Could this package achieve covariate adjusted KM survival curves for competing risk events analysis?

**Comment by RobinDenz1** [comment]
I am glad to hear that you like it. Unfortunately what you are asking for is currently impossible. There is no known way to get unbiased estimates of the cause-specific survival function in the competing risks setting (see for example https://pubmed.ncbi.nlm.nih.gov/15305188/ or the textbook by Beyersmann et al. https://link.springer.com/book/10.1007/978-1-4614-2035-4 for more information.

Since there is no unadjusted version of this function, there is also no way to get confounder-adjusted versions of this function.

You may, however, use the `adjustedcif` function to obtain confounder-adjusted cause-specific cumulative incidence functions.

Hope this helps!
