### ISSUE TITLE
facet_grid

### ISSUE THREAD

**Issue by hermionewarr** [RobinDenz1/adjustedCurves#7]
Hi, is it possible to make this work with other ggsurvplot functionality such as theme and facet_grid(variable)? 
Thanks for the confidence intervals (super handy!)

**Comment by RobinDenz1** [comment]
I am not sure what exactly you are asking for, so I am gonna guess.

If you want to set a theme to the resulting plot, you can use the `gg_theme` argument of the `plot` function, or directly add a new theme to the output object like `plot(adjsurv) + theme_bw()`. If you want the plot to be facetted using the `variable` as facets, you can use `facet=TRUE` in the `plot` function. This is explained in deatil in the documentation of this package (see `?plot.adjustedsurv`).

Is this what you were looking for? Or are you talking about something else?

**Comment by hermionewarr** [comment]
Ah no sorry, I meant whether it would be possible to facet by another variable in the cox model? Say outcome ~ main_variable + other_variables and I want survival plots stratified by the main variable displayed on separate plots for one of the other model variables (facet_grid(~other_var) )? Sorry for not being very clear!

**Comment by RobinDenz1** [comment]
No problem, I get it now.

There is unfortunately no direct way to do this with the `adjustedCurves` package. As I see it you have two options. Which one is best suited to you depends on what exactly you are trying to estimate.

1.) Fit one separate Cox model for each stratum of the second variable. Estimate and plot the adjusted survival curves using `adjustedsurv` and the associated `plot` method for each of the strata separately. Safe the resulting `ggplot2` objects and combine them using something like `ggarrange` from the `ggpubr` package. This works well if you think that there is *effect modification* but no actual *effect interaction* between your main variable of interest and the grouping variable. If you want the `facet_grid` look instead of the `ggarrange` look, you could also extract the estimates from all `adjustedsurv` objects separately, combine them and use your own plot function. Something like this:
```
est_1 <- adjsurv_strata_A$adjsurv
est_2 <- adjsurv_strata_B$adjsurv

est_1$strata <- "A"
est_2$strata <- "B"

plotdata <- rbind(est_1, est_2)
ggplot(plotdata, aes(x=time, y=surv, color=variable)) +
  geom_step() +
  facet_wrap(~strata)
```

2.) Create an interaction term between the main variable of interest and the strata variable using the `interaction()` function, add this to your data. Include this interaction term in your Cox model instead of including the variables separately. Use this variable as the main variable of interest. This works well if you assume that there is an actual interaction effect between the two variables. You can now use the standard `plot` function to get one curve for each combination. If you insist on using one facet per strata and different colors per variable of interest, you could again extract the results of the `adjustedsurv` object and use your own plot function, like this:
```
plotdata <- adjsurv_obj$adjsurv

# separate the interaction variable into its parts using some gsub() calls or something similar,
# what I did here wouldn't work, it's merely meant as an example
plotdata$var_interest <- gsub(plotdata$variable)
plotdata$strata <- gsub(plotdata$variable)

ggplot(plotdata, aes(x=time, y=surv, color=var_interest) +
   geom_step() +
   facet_wrap(~strata)
```
I hope this helps. If some of this is unclear to you, I am happy to answer follow-up questions.

**Comment by hermionewarr** [comment]
Thank you - that has been very helpful! :)
